"""add error tracking and latency columns to crawl_jobs

Revision ID: c360b11bc6e4
Revises: 0007_add_alerts_table
Create Date: 2026-06-23 15:16:24.321418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c360b11bc6e4'
down_revision: Union[str, Sequence[str], None] = '0007_add_alerts_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.add_column('crawl_jobs', sa.Column('error_count_transient', sa.Integer(), nullable=True))
    op.add_column('crawl_jobs', sa.Column('error_count_persistent', sa.Integer(), nullable=True))
    op.add_column('crawl_jobs', sa.Column('average_latency_ms', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('crawl_jobs', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_leak_records_classification'), table_name='leak_records')
    op.drop_index(op.f('ix_leak_records_risk_score'), table_name='leak_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_leak_records_risk_score'), 'leak_records', ['risk_score'], unique=False)
    op.create_index(op.f('ix_leak_records_classification'), 'leak_records', ['classification'], unique=False)
    op.alter_column('crawl_jobs', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('crawl_jobs', 'average_latency_ms')
    op.drop_column('crawl_jobs', 'error_count_persistent')
    op.drop_column('crawl_jobs', 'error_count_transient')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    # ### end Alembic commands ###
